INSERT INTO feeding_schedules (age_group, feeding_times, create_date, last_update) VALUES
('Kitten', '3 meals per day', CURRENT_DATE, CURRENT_DATE),
('Adult Cat', '2 meals per day', CURRENT_DATE, CURRENT_DATE),
('Senior Cat', '1 meal per day', CURRENT_DATE, CURRENT_DATE),
('Puppy (Under 6 Months)', '4 meals per day', CURRENT_DATE, CURRENT_DATE),
('Adult Dog', '2 meals per day', CURRENT_DATE, CURRENT_DATE),
('Senior Dog', '1-2 meals per day', CURRENT_DATE, CURRENT_DATE),
('Kittens (3-6 months)', '3 meals per day', CURRENT_DATE, CURRENT_DATE),
('Kittens (6-12 months)', '2 meals per day', CURRENT_DATE, CURRENT_DATE),
('Small Breeds', '2 meals per day', CURRENT_DATE, CURRENT_DATE),
('Medium Breeds', '2 meals per day', CURRENT_DATE, CURRENT_DATE),
('Large Breeds', '2 meals per day', CURRENT_DATE, CURRENT_DATE),
('Giant Breeds', '2-3 meals per day', CURRENT_DATE, CURRENT_DATE),
('Adult Cats (Indoor)', '2 meals per day', CURRENT_DATE, CURRENT_DATE),
('Outdoor Cats', 'Free feeding or 2 meals per day', CURRENT_DATE, CURRENT_DATE),
('Puppy (6-12 Months)', '3 meals per day', CURRENT_DATE, CURRENT_DATE),
('Active Adult Dogs', '2 meals per day', CURRENT_DATE, CURRENT_DATE),
('Obese Dogs', '1-2 meals per day with calorie restriction', CURRENT_DATE, CURRENT_DATE),
('Pregnant Cats', '2-3 meals per day', CURRENT_DATE, CURRENT_DATE),
('Nursing Cats', 'Free feeding or multiple meals', CURRENT_DATE, CURRENT_DATE),
('Senior Cats', '1-2 meals per day', CURRENT_DATE, CURRENT_DATE),
('Puppies (Over 6 Months)', '2 meals per day', CURRENT_DATE, CURRENT_DATE),
('Working Dogs', '2 meals per day with high-quality food', CURRENT_DATE, CURRENT_DATE),
('Show Cats', '2 meals per day with premium diet', CURRENT_DATE, CURRENT_DATE),
('Show Dogs', '2 meals per day with premium diet', CURRENT_DATE, CURRENT_DATE),
('Cats with Health Issues', 'Consult with a vet for feeding schedule', CURRENT_DATE, CURRENT_DATE),
('Dogs with Health Issues', 'Consult with a vet for feeding schedule', CURRENT_DATE, CURRENT_DATE),
('Growing Kittens', '3 meals per day', CURRENT_DATE, CURRENT_DATE),
('Adult Cats (Outdoor)', 'Free feeding or 2 meals per day', CURRENT_DATE, CURRENT_DATE),
('Sensitive Stomach Dogs', 'Smaller, more frequent meals', CURRENT_DATE, CURRENT_DATE),
('Fat Cats', '1 meal per day with calorie restriction', CURRENT_DATE, CURRENT_DATE),
('Puppy Training Nutrition', 'Frequent meals to support growth', CURRENT_DATE, CURRENT_DATE),
('Senior Dogs', '1-2 meals per day', CURRENT_DATE, CURRENT_DATE),
('Rescue Cats', 'Free feeding or multiple meals', CURRENT_DATE, CURRENT_DATE),
('Rescue Dogs', 'Free feeding or multiple meals', CURRENT_DATE, CURRENT_DATE),
('Foster Kittens', '3-4 meals per day', CURRENT_DATE, CURRENT_DATE),
('Foster Puppies', '4 meals per day', CURRENT_DATE, CURRENT_DATE),
('Dogs with Allergies', 'Consult with a vet for special diet', CURRENT_DATE, CURRENT_DATE),
('Cats with Allergies', 'Consult with a vet for special diet', CURRENT_DATE, CURRENT_DATE),
('Active Cats', '2 meals per day', CURRENT_DATE, CURRENT_DATE),
('Senior Dogs with Health Issues', '1 meal per day with special diet', CURRENT_DATE, CURRENT_DATE),
('Obese Cats', '1 meal per day with calorie restriction', CURRENT_DATE, CURRENT_DATE),
('Post-Surgery Pets', 'Small, frequent meals', CURRENT_DATE, CURRENT_DATE),
('Newly Adopted Cats', 'Free feeding for adjustment', CURRENT_DATE, CURRENT_DATE),
('Newly Adopted Dogs', 'Free feeding for adjustment', CURRENT_DATE, CURRENT_DATE),
('Cats with Dental Issues', 'Soft food recommended', CURRENT_DATE, CURRENT_DATE),
('Dogs with Dental Issues', 'Soft food recommended', CURRENT_DATE, CURRENT_DATE);


INSERT INTO training_guides (title, content, create_date, last_update) VALUES
('Basic Cat Training', 'Learn the fundamentals of training your cat, including litter box training and basic commands.', CURRENT_DATE, CURRENT_DATE),
('Dog Obedience Training', 'Essential commands for your dog to follow, ensuring a well-behaved pet.', CURRENT_DATE, CURRENT_DATE),
('Cat Behavior Modification', 'Techniques to address unwanted behaviors in cats.', CURRENT_DATE, CURRENT_DATE),
('Advanced Dog Tricks', 'Teach your dog to perform advanced tricks and commands.', CURRENT_DATE, CURRENT_DATE),
('Puppy Training Essentials', 'Everything you need to know for training your new puppy.', CURRENT_DATE, CURRENT_DATE),
('Grooming Your Cat', 'A guide on how to groom your cat for a healthy coat.', CURRENT_DATE, CURRENT_DATE),
('Leash Training for Dogs', 'Tips for successfully leash training your dog.', CURRENT_DATE, CURRENT_DATE),
('Cat Socialization Techniques', 'How to help your cat get along with other pets.', CURRENT_DATE, CURRENT_DATE),
('Dog Agility Training', 'An introduction to agility training for dogs.', CURRENT_DATE, CURRENT_DATE),
('Understanding Cat Body Language', 'Learn what your cat is trying to communicate with its body language.', CURRENT_DATE, CURRENT_DATE),
('Dog Nutrition and Training', 'The importance of nutrition in a dog’s training regimen.', CURRENT_DATE, CURRENT_DATE),
('Building a Strong Bond with Your Dog', 'Activities that strengthen the bond between you and your dog.', CURRENT_DATE, CURRENT_DATE),
('Feline Enrichment Activities', 'Fun activities to keep your cat mentally stimulated.', CURRENT_DATE, CURRENT_DATE),
('Positive Reinforcement Training for Dogs', 'Using positive reinforcement to train your dog.', CURRENT_DATE, CURRENT_DATE),
('Introducing a New Pet to Your Cat', 'Steps to ensure a smooth introduction of a new pet.', CURRENT_DATE, CURRENT_DATE),
('Basic Commands for Cats', 'Teach your cat basic commands like sit and stay.', CURRENT_DATE, CURRENT_DATE),
('Dog Safety and First Aid', 'Essential safety tips and first aid for your dog.', CURRENT_DATE, CURRENT_DATE),
('Understanding Your Dog’s Needs', 'How to read and respond to your dog’s needs.', CURRENT_DATE, CURRENT_DATE),
('Fostering Good Behavior in Cats', 'Tips to encourage positive behavior in your feline friend.', CURRENT_DATE, CURRENT_DATE),
('Socializing Your Puppy', 'The importance of socialization for young dogs.', CURRENT_DATE, CURRENT_DATE),
('Cat Trick Training', 'Fun tricks you can teach your cat.', CURRENT_DATE, CURRENT_DATE),
('Traveling with Pets', 'How to prepare and train your pet for travel.', CURRENT_DATE, CURRENT_DATE),
('Dog Park Etiquette', 'How to behave at the dog park for a pleasant experience.', CURRENT_DATE, CURRENT_DATE),
('Creating a Safe Home for Your Cat', 'Tips to cat-proof your home.', CURRENT_DATE, CURRENT_DATE),
('Understanding Canine Behavior', 'Learn the basics of canine behavior and psychology.', CURRENT_DATE, CURRENT_DATE),
('Potty Training for Puppies', 'Effective techniques for potty training your puppy.', CURRENT_DATE, CURRENT_DATE),
('Choosing the Right Toys for Cats', 'How to choose toys that keep your cat engaged.', CURRENT_DATE, CURRENT_DATE),
('Dog Training Myths Debunked', 'Common misconceptions about dog training.', CURRENT_DATE, CURRENT_DATE),
('How to Calm an Anxious Dog', 'Techniques to help soothe anxious dogs.', CURRENT_DATE, CURRENT_DATE),
('Cats and Playtime', 'The importance of playtime for cats.', CURRENT_DATE, CURRENT_DATE),
('Dog Nutrition Basics', 'Understanding the nutritional needs of your dog.', CURRENT_DATE, CURRENT_DATE),
('Creating a Training Schedule', 'How to set a training schedule for your pet.', CURRENT_DATE, CURRENT_DATE),
('Teaching Your Dog to Fetch', 'A step-by-step guide to teaching your dog to fetch.', CURRENT_DATE, CURRENT_DATE),
('Maintaining Your Cat’s Health', 'Routine care for a healthy cat.', CURRENT_DATE, CURRENT_DATE),
('Understanding Feline Nutrition', 'What to feed your cat for optimal health.', CURRENT_DATE, CURRENT_DATE),
('Tips for a Happy Dog', 'Ways to ensure your dog is happy and healthy.', CURRENT_DATE, CURRENT_DATE),
('Behavioral Issues in Dogs', 'How to address common behavioral problems.', CURRENT_DATE, CURRENT_DATE),
('Cat Communication 101', 'Understanding how cats communicate with their owners.', CURRENT_DATE, CURRENT_DATE),
('Preparing Your Dog for a New Baby', 'How to get your dog ready for the arrival of a new baby.', CURRENT_DATE, CURRENT_DATE),
('Hydration for Cats', 'Importance of water and hydration for your cat.', CURRENT_DATE, CURRENT_DATE),
('Training Older Dogs', 'Tips for training senior dogs.', CURRENT_DATE, CURRENT_DATE),
('Common Health Problems in Cats', 'Recognizing and addressing health issues in cats.', CURRENT_DATE, CURRENT_DATE),
('Behavioral Training for Dogs', 'Advanced techniques for dog behavioral training.', CURRENT_DATE, CURRENT_DATE),
('Interactive Play for Cats', 'Ways to engage your cat in interactive play.', CURRENT_DATE, CURRENT_DATE),
('Dog-Friendly Activities', 'Fun activities to do with your dog.', CURRENT_DATE, CURRENT_DATE),
('Understanding Cat Breeds', 'Characteristics of various cat breeds.', CURRENT_DATE, CURRENT_DATE),
('Dog Show Basics', 'Getting started with dog shows and competitions.', CURRENT_DATE, CURRENT_DATE);


INSERT INTO users (name, email, password, create_date, last_update) VALUES
('John Doe', 'john.doe@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Jane Smith', 'jane.smith@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Alice Johnson', 'alice.johnson@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Bob Brown', 'bob.brown@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Charlie Davis', 'charlie.davis@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Emily Clark', 'emily.clark@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('David Wilson', 'david.wilson@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Sophia Miller', 'sophia.miller@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('James Taylor', 'james.taylor@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Olivia Anderson', 'olivia.anderson@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Michael Thomas', 'michael.thomas@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Isabella Moore', 'isabella.moore@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('William Jackson', 'william.jackson@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Mia Harris', 'mia.harris@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Ethan Martin', 'ethan.martin@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Ava Thompson', 'ava.thompson@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Lucas Garcia', 'lucas.garcia@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Emma Martinez', 'emma.martinez@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Liam Robinson', 'liam.robinson@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Chloe Lewis', 'chloe.lewis@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Noah Lee', 'noah.lee@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Avery Walker', 'avery.walker@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Oliver Hall', 'oliver.hall@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Sophia Allen', 'sophia.allen@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Elijah Young', 'elijah.young@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Lily King', 'lily.king@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Benjamin Wright', 'benjamin.wright@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Grace Scott', 'grace.scott@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Henry Green', 'henry.green@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Scarlett Adams', 'scarlett.adams@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Alexander Baker', 'alexander.baker@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Ella Gonzalez', 'ella.gonzalez@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Jackson Nelson', 'jackson.nelson@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Zoe Carter', 'zoe.carter@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Daniel Mitchell', 'daniel.mitchell@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Samantha Perez', 'samantha.perez@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Matthew Roberts', 'matthew.roberts@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Hannah Turner', 'hannah.turner@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Isaiah Phillips', 'isaiah.phillips@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Natalie Campbell', 'natalie.campbell@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('David Parker', 'david.parker@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Victoria Evans', 'victoria.evans@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Samuel Edwards', 'samuel.edwards@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Megan Edwards', 'megan.edwards@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Emily Cox', 'emily.cox@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Michael Rivera', 'michael.rivera@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Claire Fisher', 'claire.fisher@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Oliver Gomez', 'oliver.gomez@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Sophie Long', 'sophie.long@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Jack Murphy', 'jack.murphy@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Nora Wells', 'nora.wells@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Carter Ward', 'carter.ward@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Emily Simmons', 'emily.simmons@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('David Rivera', 'david.rivera@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Emma Johnson', 'emma.johnson@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Mason Lee', 'mason.lee@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Grace Parker', 'grace.parker@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Lily Scott', 'lily.scott@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Aiden Young', 'aiden.young@example.com', 'password123', CURRENT_DATE, CURRENT_DATE),
('Sophie Wright', 'sophie.wright@example.com', 'password123', CURRENT_DATE, CURRENT_DATE);



INSERT INTO reviews (cat_breed_id, dog_breed_id, user_id, rating, comment, create_date, last_update) VALUES
(1, NULL, 1, 5, 'Great breed! Very affectionate.', CURRENT_DATE, CURRENT_DATE),
(2, NULL, 2, 4, 'Very playful and energetic.', CURRENT_DATE, CURRENT_DATE),
(3, NULL, 3, 3, 'Good companion, but needs training.', CURRENT_DATE, CURRENT_DATE),
(4, NULL, 4, 5, 'Loves to cuddle and play!', CURRENT_DATE, CURRENT_DATE),
(5, NULL, 5, 4, 'Very loyal and protective.', CURRENT_DATE, CURRENT_DATE),
(6, NULL, 6, 2, 'Too aggressive for my taste.', CURRENT_DATE, CURRENT_DATE),
(7, NULL, 7, 5, 'Best cat I ever had!', CURRENT_DATE, CURRENT_DATE),
(8, NULL, 8, 4, 'Very smart and easy to train.', CURRENT_DATE, CURRENT_DATE),
(9, NULL, 9, 3, 'Average, but cute.', CURRENT_DATE, CURRENT_DATE),
(10, NULL, 10, 5, 'Fantastic breed for families.', CURRENT_DATE, CURRENT_DATE),
(11, NULL, 11, 4, 'Friendly and social.', CURRENT_DATE, CURRENT_DATE),
(12, NULL, 12, 3, 'Needs more exercise.', CURRENT_DATE, CURRENT_DATE),
(13, NULL, 13, 5, 'Loves kids and other pets.', CURRENT_DATE, CURRENT_DATE),
(14, NULL, 14, 4, 'Very trainable and smart.', CURRENT_DATE, CURRENT_DATE),
(15, NULL, 15, 2, 'Not what I expected.', CURRENT_DATE, CURRENT_DATE),
(16, NULL, 16, 5, 'An amazing companion.', CURRENT_DATE, CURRENT_DATE),
(17, NULL, 17, 4, 'Great with children.', CURRENT_DATE, CURRENT_DATE),
(18, NULL, 18, 3, 'Could be better with training.', CURRENT_DATE, CURRENT_DATE),
(19, NULL, 19, 5, 'Absolutely love this breed!', CURRENT_DATE, CURRENT_DATE),
(20, NULL, 20, 4, 'Very affectionate and loyal.', CURRENT_DATE, CURRENT_DATE),
(21, NULL, 21, 3, 'A bit stubborn at times.', CURRENT_DATE, CURRENT_DATE),
(22, NULL, 22, 5, 'Perfect for first-time owners.', CURRENT_DATE, CURRENT_DATE),
(23, NULL, 23, 4, 'Energetic and playful.', CURRENT_DATE, CURRENT_DATE),
(24, NULL, 24, 3, 'Needs daily exercise.', CURRENT_DATE, CURRENT_DATE),
(25, NULL, 25, 5, 'Super friendly and loving.', CURRENT_DATE, CURRENT_DATE),
(26, NULL, 26, 4, 'Good watchdog and family pet.', CURRENT_DATE, CURRENT_DATE),
(27, NULL, 27, 2, 'Not very sociable.', CURRENT_DATE, CURRENT_DATE),
(28, NULL, 28, 5, 'Incredible personality.', CURRENT_DATE, CURRENT_DATE),
(29, NULL, 29, 4, 'Great with other pets.', CURRENT_DATE, CURRENT_DATE),
(30, NULL, 30, 3, 'A bit high maintenance.', CURRENT_DATE, CURRENT_DATE),
(NULL, 1, 31, 5, 'Great companion for families!', CURRENT_DATE, CURRENT_DATE),
(NULL, 2, 32, 4, 'Very playful and friendly.', CURRENT_DATE, CURRENT_DATE),
(NULL, 3, 33, 3, 'Good watchdog but needs training.', CURRENT_DATE, CURRENT_DATE),
(NULL, 4, 34, 5, 'Loves to be outdoors and run!', CURRENT_DATE, CURRENT_DATE),
(NULL, 5, 35, 4, 'Very loyal and easy to train.', CURRENT_DATE, CURRENT_DATE),
(NULL, 6, 36, 2, 'Too energetic for my lifestyle.', CURRENT_DATE, CURRENT_DATE),
(NULL, 7, 37, 5, 'Amazing temperament and very loving.', CURRENT_DATE, CURRENT_DATE),
(NULL, 8, 38, 4, 'Good with kids and other pets.', CURRENT_DATE, CURRENT_DATE),
(NULL, 9, 39, 3, 'Average experience, not very active.', CURRENT_DATE, CURRENT_DATE),
(NULL, 10, 40, 5, 'Best dog I have ever owned!', CURRENT_DATE, CURRENT_DATE),
(NULL, 11, 41, 4, 'Very friendly and social with strangers.', CURRENT_DATE, CURRENT_DATE),
(NULL, 12, 42, 3, 'Needs a lot of exercise to stay happy.', CURRENT_DATE, CURRENT_DATE),
(NULL, 13, 43, 5, 'Fantastic with children and other animals.', CURRENT_DATE, CURRENT_DATE),
(NULL, 14, 44, 4, 'Good family dog, needs some training.', CURRENT_DATE, CURRENT_DATE),
(NULL, 15, 45, 2, 'Not as affectionate as I expected.', CURRENT_DATE, CURRENT_DATE),
(NULL, 16, 46, 5, 'An incredible addition to our family!', CURRENT_DATE, CURRENT_DATE),
(NULL, 17, 47, 4, 'Very intelligent and quick learner.', CURRENT_DATE, CURRENT_DATE),
(NULL, 18, 48, 3, 'Average energy levels, could be more active.', CURRENT_DATE, CURRENT_DATE),
(NULL, 19, 49, 5, 'A joy to have around, very playful!', CURRENT_DATE, CURRENT_DATE),
(NULL, 20, 50, 4, 'Great personality, friendly to everyone.', CURRENT_DATE, CURRENT_DATE),
(NULL, 21, 51, 3, 'Needs more socialization with other dogs.', CURRENT_DATE, CURRENT_DATE),
(NULL, 22, 52, 5, 'Perfect for a first-time dog owner.', CURRENT_DATE, CURRENT_DATE),
(NULL, 23, 53, 4, 'Energetic and loves to play fetch.', CURRENT_DATE, CURRENT_DATE),
(NULL, 24, 54, 3, 'Not the best choice for small apartments.', CURRENT_DATE, CURRENT_DATE),
(NULL, 25, 55, 5, 'A loyal friend for life!', CURRENT_DATE, CURRENT_DATE),
(NULL, 26, 56, 4, 'Very playful and social with kids.', CURRENT_DATE, CURRENT_DATE),
(NULL, 27, 57, 2, 'Could be more affectionate.', CURRENT_DATE, CURRENT_DATE),
(NULL, 28, 58, 5, 'Best dog I’ve ever owned!', CURRENT_DATE, CURRENT_DATE),
(NULL, 29, 59, 4, 'Good with other animals.', CURRENT_DATE, CURRENT_DATE),
(NULL, 30, 60, 3, 'Needs more training and socialization.', CURRENT_DATE, CURRENT_DATE);


INSERT INTO user_favorite_cat_breeds (user_id, cat_breed_id) VALUES
(1, 1),
(1, 2),
(2, 3),
(2, 4),
(3, 5),
(3, 6),
(4, 7),
(4, 8),
(5, 9),
(5, 10),
(6, 11),
(6, 12),
(7, 13),
(7, 14),
(8, 15),
(8, 16),
(9, 17),
(9, 18),
(10, 19),
(10, 20),
(11, 21),
(11, 22),
(12, 23),
(12, 24),
(13, 25),
(13, 26),
(14, 27),
(14, 28),
(15, 29),
(15, 30);


INSERT INTO user_favorite_dog_breeds (user_id, dog_breed_id) VALUES
(1, 1),
(1, 2),
(2, 3),
(2, 4),
(3, 5),
(3, 6),
(4, 7),
(4, 8),
(5, 9),
(5, 10),
(6, 11),
(6, 12),
(7, 13),
(7, 14),
(8, 15),
(8, 16),
(9, 17),
(9, 18),
(10, 19),
(10, 20),
(11, 21),
(11, 22),
(12, 23),
(12, 24),
(13, 25),
(13, 26),
(14, 27),
(14, 28),
(15, 29),
(15, 30);

INSERT INTO training_guide_cat_breeds (trainingguide_id, cat_breed_id) VALUES
(1, 1),
(1, 2),
(2, 3),
(2, 4),
(3, 5),
(3, 6),
(4, 7),
(4, 8),
(5, 9),
(5, 10),
(6, 11),
(6, 12),
(7, 13),
(7, 14),
(8, 15),
(8, 16),
(9, 17),
(9, 18),
(10, 19),
(10, 20),
(11, 21),
(11, 22),
(12, 23),
(12, 24),
(13, 25),
(13, 26),
(14, 27),
(14, 28),
(15, 29),
(15, 30);

INSERT INTO training_guide_dog_breeds (trainingguide_id, dog_breed_id) VALUES
(1, 1),
(1, 2),
(2, 3),
(2, 4),
(3, 5),
(3, 6),
(4, 7),
(4, 8),
(5, 9),
(5, 10),
(6, 11),
(6, 12),
(7, 13),
(7, 14),
(8, 15),
(8, 16),
(9, 17),
(9, 18),
(10, 19),
(10, 20),
(11, 21),
(11, 22),
(12, 23),
(12, 24),
(13, 25),
(13, 26),
(14, 27),
(14, 28),
(15, 29),
(15, 30);
